version: '3.8'

services:
  # ==========================================
  # SERVICIO 1: La Base de Datos MySQL
  # ==========================================
  db:
    image: mysql:8.0
    container_name: beachg-mysql
    environment:
      MYSQL_DATABASE: beachg_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      # Exponemos el puerto 3307 en tu compu para que no choque con tu MySQL local
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ==========================================
  # SERVICIO 2: Tu Backend Spring Boot
  # ==========================================
  backend:
    build: . # Le dice que cocine el Dockerfile que creamos antes
    container_name: beachg-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Magia de Spring Boot: Estas variables pisan a tu application.properties
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/beachg_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Le pasamos el token de Mercado Pago desde tu archivo .env
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      NGROK_BASE_URL: ${NGROK_BASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  # Esto guarda la info para que las reservas no se borren si apagás la compu
  db_data: